// <auto-generated />
using System;
using ArcaiProject.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcaiProject.DataAccess.Migrations
{
    [DbContext(typeof(ArcaiDbContext))]
    [Migration("20251124202840_AddSoftDeleteProperties")]
    partial class AddSoftDeleteProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArcaiProject.Entities.Entities.AcademicPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PeriodName")
                        .IsUnique();

                    b.ToTable("AcademicPeriods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PeriodName = "2023-2024 Fall"
                        },
                        new
                        {
                            Id = 2,
                            PeriodName = "2023-2024 Spring"
                        },
                        new
                        {
                            Id = 3,
                            PeriodName = "2024-2025 Fall"
                        });
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.BorrowingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckoutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("RequesterUserId");

                    b.ToTable("BorrowingRecords");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCode = "CEN403",
                            CourseName = "Software Design",
                            Department = "Computer Engineering"
                        },
                        new
                        {
                            Id = 2,
                            CourseCode = "MT101",
                            CourseName = "Calculus I",
                            Department = "Basic Sciences"
                        },
                        new
                        {
                            Id = 3,
                            CourseCode = "CEN305",
                            CourseName = "Database Systems",
                            Department = "Computer Engineering"
                        });
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPeriodId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.DocumentTag", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("DocumentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("DocumentTags");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Midterm (ara sınav) exam papers.",
                            Name = "Midterm Exam Paper"
                        },
                        new
                        {
                            Id = 2,
                            Description = "End-of-term (final) exam papers.",
                            Name = "Final Exam Paper"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Student internship reports and logbooks.",
                            Name = "Internship Report"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Official faculty administrative documents.",
                            Name = "Administrative Document"
                        });
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cabinet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shelf")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FriendlyName")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cabinet = "Cabinet A",
                            FriendlyName = "Room 205 - Cabinet A - Shelf 1",
                            Room = "Room 205",
                            Shelf = "Shelf 1"
                        },
                        new
                        {
                            Id = 2,
                            Cabinet = "Cabinet A",
                            FriendlyName = "Room 205 - Cabinet A - Shelf 2",
                            Room = "Room 205",
                            Shelf = "Shelf 2"
                        },
                        new
                        {
                            Id = 3,
                            Cabinet = "Cabinet B",
                            FriendlyName = "Room 205 - Cabinet B - Shelf 1",
                            Room = "Room 205",
                            Shelf = "Shelf 1"
                        });
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Theoretical"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Practical"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Project"
                        },
                        new
                        {
                            Id = 4,
                            Name = "MultipleChoice"
                        });
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "secretary@arcai.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "Secretary",
                            PasswordHash = "AQAAAAIAAYagAAAAENn+B2BvDgeN3A3S/jAfXqfA+kQ6/bA8qTLcOhmfI4YqKE1XlK0/j8H+c0D+A9p+QQ==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.smith@arcai.com",
                            FirstName = "Prof. John",
                            IsActive = true,
                            LastName = "Smith",
                            PasswordHash = "AQAAAAIAAYagAAAAEMp/yC0m8Cg1Q2bH8V/4l1EK1fB/iYqSKc2iBCcBOy1F0Pq+Yqf/QYQ3aN6xXqGvIQ==",
                            Role = "Professor"
                        });
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.BorrowingRecord", b =>
                {
                    b.HasOne("ArcaiProject.Entities.Entities.User", "ApproverUser")
                        .WithMany("ApprovedRecords")
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArcaiProject.Entities.Entities.Document", "Document")
                        .WithMany("BorrowingRecords")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaiProject.Entities.Entities.User", "RequesterUser")
                        .WithMany("RequestedRecords")
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("Document");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Document", b =>
                {
                    b.HasOne("ArcaiProject.Entities.Entities.AcademicPeriod", "AcademicPeriod")
                        .WithMany("Documents")
                        .HasForeignKey("AcademicPeriodId");

                    b.HasOne("ArcaiProject.Entities.Entities.User", "AddedByUser")
                        .WithMany("DocumentsAdded")
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaiProject.Entities.Entities.Course", "Course")
                        .WithMany("Documents")
                        .HasForeignKey("CourseId");

                    b.HasOne("ArcaiProject.Entities.Entities.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaiProject.Entities.Entities.Location", "Location")
                        .WithMany("Documents")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicPeriod");

                    b.Navigation("AddedByUser");

                    b.Navigation("Course");

                    b.Navigation("DocumentType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.DocumentTag", b =>
                {
                    b.HasOne("ArcaiProject.Entities.Entities.Document", "Document")
                        .WithMany("DocumentTags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcaiProject.Entities.Entities.Tag", "Tag")
                        .WithMany("DocumentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Notification", b =>
                {
                    b.HasOne("ArcaiProject.Entities.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.AcademicPeriod", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Course", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Document", b =>
                {
                    b.Navigation("BorrowingRecords");

                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Location", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.Tag", b =>
                {
                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("ArcaiProject.Entities.Entities.User", b =>
                {
                    b.Navigation("ApprovedRecords");

                    b.Navigation("DocumentsAdded");

                    b.Navigation("RequestedRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
